name = "Messenger Wrapped"
description = "Analyze Messenger history locally in browser"

[files]
"messenger_wrapped_dm/__init__.py" = "./messenger_wrapped_dm/__init__.py"
"messenger_wrapped_dm/metrics.py" = "./messenger_wrapped_dm/metrics.py"
"messenger_wrapped_dm/parser.py" = "./messenger_wrapped_dm/parser.py"
"messenger_wrapped_dm/report.py" = "./messenger_wrapped_dm/report.py"
"messenger_wrapped_dm/text.py" = "./messenger_wrapped_dm/text.py"
"messenger_wrapped_dm/sentiment_model.py" = "./messenger_wrapped_dm/sentiment_model.py"
"design_new.html" = "./design_new.html"
